version: '3'

services:
  postgres:
    image: postgres:16.3-alpine
    restart: always
    networks:
      mswServiceGradleNet:
        ipv4_address: 10.9.0.20
    environment:
      POSTGRES_USER: 'develop'
      POSTGRES_PASSWORD: 'develop'
      PGDATA: '/var/lib/postgresql/data/pgdata'
      POSTGRES_MULTIPLE_DATABASES: 'backend:password:msw,gradle:password:gradlecodegen,test:password:test'
    volumes:
      - ./localdev/data/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    ports:
      - '7010:5432'

networks:
  mswServiceGradleNet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.9.0.0/16