version: '3'

services:
  msw-postgres:
    container_name: msw-postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: 'develop'
      POSTGRES_PASSWORD: 'develop'
      PGDATA: '/var/lib/postgresql/data/pgdata'
      POSTGRES_MULTIPLE_DATABASES: 'backend:password:msw,gradle:password:gradlecodegen,test:password:test'
    volumes:
      - ./localdev/data/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    ports:
      - '5432:5432'
