openapi: 3.0.3
info:
  title: Msw Api
  description: Msw Api
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/'
paths:
  /sample/current/{stationId}:
    get:
      summary: Get current Flow and Temperature of a specific Station
      operationId: getCurrentSample
      parameters:
        - name: stationId
          description: The id of the station to get the sample from.
          in: path
          schema:
            type: integer
          required: true
      tags:
        - currentSample
      responses:
        '200':
          description: Returns the last measured Sample from the station.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSample'

  /forecast/{stationId}:
    get:
      summary: Get Forecast for specific Station
      operationId: getForecast
      parameters:
        - name: stationId
          description: The id of the station to get the sample from.
          in: path
          schema:
            type: integer
          required: true
      tags:
        - forecast
      responses:
        '200':
          description: Returns the forecast for the station.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiForecast'
  /spots:
    get:
      summary: Get SpotInformation-List including Current Sample and Forecast.
      operationId: getSpots
      parameters:
        - name: includeAll
          description: Whether to include all Spots.
          in: query
          schema:
            type: boolean
          required: false
      tags:
        - spots
      responses:
        '200':
          description: Returns a List with Data for the Spots.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSpotInformationList'

components:
  schemas:
    ApiSpotInformationList:
      type: object
      properties:
        riverSurfSpots:
          type: array
          items:
            $ref: '#/components/schemas/ApiSpotInformation'
        bungeeSurfSpots:
          type: array
          items:
            $ref: '#/components/schemas/ApiSpotInformation'
    ApiSpotInformation:
      type: object
      properties:
        name:
          type: string
        stationId:
          type: integer
        minFlow:
          type: integer
        maxFlow:
          type: integer
        currentSample:
          $ref: '#/components/schemas/ApiSample'
        forecast:
          $ref: '#/components/schemas/ApiForecast'
    ApiSample:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        temperature:
          type: number
          format: double
        flow:
          type: integer
    ApiForecast:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        measuredData:
          type: array
          items:
            $ref: '#/components/schemas/ApiForecastLineEntry'
        median:
          type: array
          items:
            $ref: '#/components/schemas/ApiForecastLineEntry'
        twentyFivePercentile:
          type: array
          items:
            $ref: '#/components/schemas/ApiForecastLineEntry'
        seventyFivePercentile:
          type: array
          items:
            $ref: '#/components/schemas/ApiForecastLineEntry'
        max:
          type: array
          items:
            $ref: '#/components/schemas/ApiForecastLineEntry'
        min:
          type: array
          items:
            $ref: '#/components/schemas/ApiForecastLineEntry'
    ApiForecastLineEntry:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        flow:
          type: number
          format: double
