openapi: 3.0.3
info:
  title: Msw Api
  description: Msw Api
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/'
paths:
  /api/v1/sample/lastFewDays:
    post:
      summary: Get Samples from last Few Days for this station.
      security:
        - bearerAuth: [ ]
      operationId: getLastFewDaysSamples
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: The ids of the stations to get the sample from.
              type: array
              items:
                $ref: '#/components/schemas/ApiStationId'
      tags:
        - sample
      responses:
        '200':
          description: Returns the Samples from the last Few Days for the station.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiLastFewDaysList'
  /api/v1/forecasts:
    get:
      summary: Get All Forecasts for user
      security:
        - bearerAuth: [ ]
      operationId: getForecasts
      tags:
        - forecast
      responses:
        '200':
          description: Returns forecasts for all spots of user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiForecastsList'
  /api/v1/historicalYears:
    get:
      summary: Get historical data for all spots of user.
      security:
        - bearerAuth: [ ]
      operationId: getHistoricalData
      tags:
        - historical
      responses:
        '200':
          description: Returns historical data for all spots of user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiHistoricalYearsList'
  /api/v1/spots:
    get:
      summary: Get SpotInformation-List including Current Sample and Forecast for non-logged-in user.
      operationId: getSpots
      tags:
        - spots
      responses:
        '200':
          description: Returns a List with Data for the Spots.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSpotInformationList'
  /api/v1/spot:
    post:
      summary: Add a new private Spot.
      security:
        - bearerAuth: [ ]
      operationId: addPrivateSpot
      tags:
        - spots
      requestBody:
        description: The new private Spot.
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [ spot, position ]
              properties:
                spot:
                  $ref: '#/components/schemas/ApiSpot'
                position:
                  type: integer
      responses:
        '200':
          description: Added private Spot successfully.
  /api/v1/spot/{spotId}:
    patch:
      summary: Edit a private spot.
      security:
        - bearerAuth: [ ]
      operationId: editPrivateSpot
      parameters:
        - name: spotId
          description: The id of the spot to edit.
          in: path
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        description: The updated private spot.
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [ spot ]
              properties:
                spot:
                  $ref: '#/components/schemas/ApiSpot'
      tags:
        - spots
      responses:
        '200':
          description: Edited private spot successfully.
    delete:
      summary: Remove a private spot.
      security:
        - bearerAuth: [ ]
      operationId: deletePrivateSpot
      parameters:
        - name: spotId
          description: The id of the spot to delete.
          in: path
          schema:
            type: string
            format: uuid
          required: true
      tags:
        - spots
      responses:
        '200':
          description: Removed private spot successfully.
  /api/v1/spots/order:
    patch:
      summary: Change the order of the spots
      security:
        - bearerAuth: [ ]
      requestBody:
        description: The new order of the spots.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpotOrderList'
      operationId: orderSpots
      tags:
        - spots
      responses:
        '200':
          description: Ordered spots successfully
  /api/v1/user/register:
    post:
      summary: Register new User.
      operationId: registerUser
      tags:
        - user
      responses:
        '200':
          description: Registration was successful.
  /api/v1/stations:
    get:
      summary: Get a list of stations from BAFU
      operationId: getStations
      tags:
        - station
      responses:
        '200':
          description: Returns a list of stations from BAFU.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiStationList'
  /api/v1/notifications/register:
    post:
      summary: Register for Push-Notifications
      security:
        - bearerAuth: [ ]
      operationId: registerForPushNotifications
      tags:
        - notifications
      requestBody:
        description: The Subscription.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PushNotificationSubscription'
      responses:
        '200':
          description: Subscribed successfully.

components:
  schemas:
    ApiSpotInformationList:
      type: array
      items:
        $ref: '#/components/schemas/ApiSpotInformation'
    ApiSpot:
      type: object
      required: [ id, name, stationId, spotType, isPublic, minFlow, maxFlow, station, withNotification ]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        stationId:
          $ref: '#/components/schemas/ApiStationId'
        spotType:
          type: string
          enum:
            - RIVER_SURF
            - BUNGEE_SURF
        isPublic:
          type: boolean
        minFlow:
          type: integer
        maxFlow:
          type: integer
        station:
          $ref: '#/components/schemas/ApiStation'
        withNotification:
          type: boolean
    ApiSpotInformation:
      allOf:
        - $ref: '#/components/schemas/ApiSpot'
        - type: object
          required: [ currentSample, flowStatusEnum ]
          properties:
            currentSample:
              $ref: '#/components/schemas/ApiSample'
            flowStatusEnum:
              $ref: '#/components/schemas/ApiFlowStatusEnum'
    ApiFlowStatusEnum:
      type: string
      nullable: false
      enum:
        - GOOD
        - BAD
        - TENDENCY_TO_BECOME_GOOD
    CountryEnum:
      type: string
      nullable: false
      enum:
        - CH
        - FR
    ApiStationId:
      type: object
      required: [ country, externalId ]
      properties:
        country:
          $ref: '#/components/schemas/CountryEnum'
        externalId:
          type: string
    SpotOrderList:
      type: array
      required: [ type, format ]
      items:
        type: string
        format: uuid
    ApiSample:
      type: object
      required: [ timestamp, flow ]
      properties:
        timestamp:
          type: string
          format: date-time
        temperature:
          type: number
          format: double
        flow:
          type: integer
    ApiFlowSample:
      type: object
      required: [ timestamp, flow ]
      properties:
        timestamp:
          type: string
          format: date-time
        flow:
          type: number
          format: double
    ApiLastFewDaysSamples:
      type: array
      items:
        $ref: '#/components/schemas/ApiFlowSample'
    ApiForecast:
      type: object
      required: [ timestamp, measuredData, median, twentyFivePercentile, seventyFivePercentile, max, min ]
      properties:
        timestamp:
          type: string
          format: date-time
        measuredData:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
        median:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
        twentyFivePercentile:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
        seventyFivePercentile:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
        max:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
        min:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
    ApiForecastsList:
      type: array
      items:
        $ref: '#/components/schemas/StationToApiForecasts'
    StationToApiForecasts:
      type: object
      required: [ station, forecast ]
      properties:
        station:
          $ref: '#/components/schemas/ApiStationId'
        forecast:
          $ref: '#/components/schemas/ApiForecast'
    ApiLastFewDaysList:
      type: array
      items:
        $ref: '#/components/schemas/StationToLastFewDays'
    StationToLastFewDays:
      type: object
      required: [ station, lastFewDays ]
      properties:
        station:
          $ref: '#/components/schemas/ApiStationId'
        lastFewDays:
          $ref: '#/components/schemas/ApiLastFewDaysSamples'
    ApiHistoricalYearsList:
      type: array
      items:
        $ref: '#/components/schemas/StationToApiHistoricalYears'
    StationToApiHistoricalYears:
      type: object
      required: [ station, historical ]
      properties:
        station:
          $ref: '#/components/schemas/ApiStationId'
        historical:
          $ref: '#/components/schemas/ApiHistoricalYears'
    ApiHistoricalYears:
      type: object
      required: [ median, twentyFivePercentile, seventyFivePercentile, max, min, currentYear ]
      properties:
        median:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
        twentyFivePercentile:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
        seventyFivePercentile:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
        max:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
        min:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
        currentYear:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
    ApiLineEntry:
      type: object
      required: [ timestamp, flow ]
      properties:
        timestamp:
          type: string
          format: date-time
        flow:
          type: number
          format: double
    ApiStationList:
      type: array
      items:
        $ref: '#/components/schemas/ApiStation'
    ApiStation:
      type: object
      required: [ id, label, latitude, longitude ]
      properties:
        id:
          $ref: '#/components/schemas/ApiStationId'
        label:
          type: string
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
    PushNotificationSubscription:
      type: object
      required: [ token ]
      properties:
        token:
          type: string

