openapi: 3.0.3
info:
  title: Msw Api
  description: Msw Api
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/'
paths:
  /api/v1/sample/current/{stationId}:
    get:
      summary: Get current Flow and Temperature of a specific Station
      security:
        - bearerAuth: [ ]
      operationId: getCurrentSample
      parameters:
        - name: stationId
          description: The id of the station to get the sample from.
          in: path
          schema:
            type: integer
          required: true
      tags:
        - sample
      responses:
        '200':
          description: Returns the last measured Sample from the station.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSample'
  /api/v1/sample/last40Days/{stationId}:
    get:
      summary: Get Samples from last 40 Days for this station.
      security:
        - bearerAuth: [ ]
      operationId: getLast40DaysSamples
      parameters:
        - name: stationId
          description: The id of the station to get the sample from.
          in: path
          schema:
            type: integer
          required: true
      tags:
        - sample
      responses:
        '200':
          description: Returns the Samples from the last 40 Days for the station.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiLast40DaysSamples'
  /api/v1/forecast/{stationId}:
    get:
      summary: Get Forecast for specific Station
      security:
        - bearerAuth: [ ]
      operationId: getForecast
      parameters:
        - name: stationId
          description: The id of the station to get the sample from.
          in: path
          schema:
            type: integer
          required: true
      tags:
        - forecast
      responses:
        '200':
          description: Returns the forecast for the station.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiForecast'
  /api/v1/spots/public:
    get:
      summary: Get SpotInformation-List including Current Sample and Forecast for non-logged-in user.
      operationId: getPublicSpots
      tags:
        - spots
      responses:
        '200':
          description: Returns a List with Data for the Spots.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSpotInformationList'
  /api/v1/spots/all:
    get:
      summary: Get Public and Private SpotInformation-List including Current Sample and Forecast for logged in user.
      security:
        - bearerAuth: [ ]
      operationId: getAllSpots
      tags:
        - spots
      responses:
        '200':
          description: Returns a List with Data for the Spots.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSpotInformationList'
  /api/v1/spot:
    post:
      summary: Add a new private Spot.
      security:
        - bearerAuth: [ ]
      operationId: addPrivateSpot
      tags:
        - spots
      requestBody:
        description: The new private Spot.
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [ spot, position ]
              properties:
                spot:
                  $ref: '#/components/schemas/ApiSpot'
                position:
                  type: integer
      responses:
        '200':
          description: Added private Spot successfully.
  /api/v1/spot/{spotId}:
    patch:
      summary: Edit a private spot.
      security:
        - bearerAuth: [ ]
      operationId: editPrivateSpot
      parameters:
        - name: spotId
          description: The id of the spot to edit.
          in: path
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        description: The updated private spot.
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [ spot ]
              properties:
                spot:
                  $ref: '#/components/schemas/ApiSpot'
      tags:
        - spots
      responses:
        '200':
          description: Edited private spot successfully.
    delete:
      summary: Remove a private spot.
      security:
        - bearerAuth: [ ]
      operationId: deletePrivateSpot
      parameters:
        - name: spotId
          description: The id of the spot to delete.
          in: path
          schema:
            type: string
            format: uuid
          required: true
      tags:
        - spots
      responses:
        '200':
          description: Removed private spot successfully.
  /api/v1/spots/order:
    patch:
      summary: Change the order of the spots
      security:
        - bearerAuth: [ ]
      requestBody:
        description: The new order of the spots.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpotOrderList'
      operationId: orderSpots
      tags:
        - spots
      responses:
        '200':
          description: Ordered spots successfully
  /api/v1/user/register:
    post:
      summary: Register new User.
      operationId: registerUser
      tags:
        - user
      responses:
        '200':
          description: Registration was successful.
  /api/v1/stations:
    get:
      summary: Get a list of stations from BAFU
      operationId: getStations
      tags:
        - station
      responses:
        '200':
          description: Returns a list of stations from BAFU.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiStationList'


components:
  schemas:
    ApiSpotInformationList:
      type: object
      required: [ riverSurfSpots, bungeeSurfSpots ]
      properties:
        riverSurfSpots:
          type: array
          items:
            $ref: '#/components/schemas/ApiSpotInformation'
        bungeeSurfSpots:
          type: array
          items:
            $ref: '#/components/schemas/ApiSpotInformation'
    ApiSpot:
      type: object
      required: [ id, name, stationId, spotType, isPublic, minFlow, maxFlow, station ]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        stationId:
          type: integer
        spotType:
          type: string
          enum:
            - RIVER_SURF
            - BUNGEE_SURF
        isPublic:
          type: boolean
        minFlow:
          type: integer
        maxFlow:
          type: integer
        station:
          $ref: '#/components/schemas/ApiStation'
    ApiSpotInformation:
      allOf:
        - $ref: '#/components/schemas/ApiSpot'
        - type: object
          required: [ currentSample, forecast, historical ]
          properties:
            currentSample:
              $ref: '#/components/schemas/ApiSample'
            forecast:
              $ref: '#/components/schemas/ApiForecast'
            historical:
              $ref: '#/components/schemas/ApiHistoricalYears'
    SpotOrderList:
      type: array
      required: [ type, format ]
      items:
        type: string
        format: uuid
    ApiSample:
      type: object
      required: [ timestamp, flow ]
      properties:
        timestamp:
          type: string
          format: date-time
        temperature:
          type: number
          format: double
        flow:
          type: integer
    ApiFlowSample:
      type: object
      required: [ timestamp, flow ]
      properties:
        timestamp:
          type: string
          format: date-time
        flow:
          type: number
          format: double
    ApiLast40DaysSamples:
      type: array
      items:
        $ref: '#/components/schemas/ApiFlowSample'
    ApiForecast:
      type: object
      required: [ timestamp, measuredData, median, twentyFivePercentile, seventyFivePercentile, max, min ]
      properties:
        timestamp:
          type: string
          format: date-time
        measuredData:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
        median:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
        twentyFivePercentile:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
        seventyFivePercentile:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
        max:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
        min:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
    ApiHistoricalYears:
      type: object
      required: [ median, twentyFivePercentile, seventyFivePercentile, max, min, currentYear ]
      properties:
        median:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
        twentyFivePercentile:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
        seventyFivePercentile:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
        max:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
        min:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
        currentYear:
          type: array
          items:
            $ref: '#/components/schemas/ApiLineEntry'
    ApiLineEntry:
      type: object
      required: [ timestamp, flow ]
      properties:
        timestamp:
          type: string
          format: date-time
        flow:
          type: number
          format: double
    ApiStationList:
      type: array
      items:
        $ref: '#/components/schemas/ApiStation'
    ApiStation:
      type: object
      required: [ id, label, latitude, longitude ]
      properties:
        id:
          type: integer
        label:
          type: string
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
