name: Verify

on:
  push:
    paths-ignore:
      - '**.md'
      - '.git/'
      - '.idea'
    pull_request:
      types:
        - opened
        - reopened
        - synchronize
        - ready_for_review

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  FIREBASE_OAUTH2_JWT_ISSUER_URI: ${{ secrets.FIREBASE_OAUTH2_JWT_ISSUER_URI }}

  GAR_LOCATION: ${{ vars.GAR_LOCATION }}
  GAR_REPOSITORY_BACKEND: ${{ vars.GAR_REPOSITORY_BACKEND }}
  GAR_REPOSITORY_FRONTEND: ${{ vars.GAR_REPOSITORY_FRONTEND }}

  FIREBASE_SERVICE_ACCOUNT_FILENAME: firebase-service-account.json

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCP_SERVICE_ACCOUNT }}

      - name: Docker configuration
        run: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://$GAR_LOCATION-docker.pkg.dev

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Start Database
        run: docker compose --project-name msw -f docker-compose.yml up -d

      - name: 🔨 Build
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: 🧪 Test
        run: |
          chmod +x ./gradlew
          ./gradlew test

      - name: 🖨️ Prepare Backend Docker Build
        run: |
          mv backend/build/libs/$(ls backend/build/libs | grep -v plain) backend/app.jar &&
          mkdir backend/config &&
          echo '${{ env.GCP_SERVICE_ACCOUNT }}' >backend/src/main/resources/${{ env.FIREBASE_SERVICE_ACCOUNT_FILENAME }}

      - name: 📝 Create application.properties-file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_spring.profiles.active: prd
          envkey_spring.application.name: msw
          envkey_spring.datasource.url: jdbc:postgresql://localhost:7010/msw
          # TODO: use secret
          envkey_spring.datasource.username: backend
          # TODO: use secret
          envkey_spring.datasource.password: password
          envkey_spring.security.oauth2.resourceserver.jwt.jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
          envkey_spring.security.oauth2.resourceserver.jwt.issuer-uri: ${{ env.FIREBASE_OAUTH2_JWT_ISSUER_URI }}
          envkey_firebase.service-account.path: ${{ env.FIREBASE_SERVICE_ACCOUNT_FILENAME }}
          file_name: application.properties
          directory: ./backend/config/

      - name: 🐳 Build Backend Docker Image
        run: |
          docker build \
            --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$GAR_REPOSITORY_BACKEND/$GITHUB_SHA" \
            --build-arg JAR_FILE=app.jar \
            backend

      - name: 🐳 Build Frontend Docker Image
        run: |
          docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$GAR_REPOSITORY_FRONTEND/$GITHUB_SHA" \
          frontend

      - name: 🚀 Push Backend Image to GCP Artifact Registry
        #        if: github.ref == 'refs/heads/master'
        run: |
          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$GAR_REPOSITORY_BACKEND/$GITHUB_SHA"

      - name: 🚀 Push Frontend Image to GCP Artifact Registry
        #        if: github.ref == 'refs/heads/master'
        run: |
          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$GAR_REPOSITORY_FRONTEND/$GITHUB_SHA"
