name: Verify

on:
  push:
    paths-ignore:
      - '**.md'
      - '.git/'
      - '.idea'
    pull_request:
      types:
        - opened
        - reopened
        - synchronize
        - ready_for_review

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Start Database
        run: docker compose --project-name msw -f docker-compose.yml up -d

      - name: 🔨 Build
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: 🧪 Test
        run: |
          chmod +x ./gradlew
          ./gradlew test
