name: Verify

on:
  push:
    paths-ignore:
      - '**.md'
      - '.git/'
      - '.idea'
    pull_request:
      types:
        - opened
        - reopened
        - synchronize
        - ready_for_review

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

  GAR_LOCATION: ${{ vars.GAR_LOCATION }}
  GAR_REPOSITORY_BACKEND: ${{ vars.GAR_REPOSITORY_BACKEND }}
  GAR_REPOSITORY_FRONTEND: ${{ vars.GAR_REPOSITORY_FRONTEND }}

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCP_SERVICE_ACCOUNT }}

      - name: Docker configuration
        run: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://$GAR_LOCATION-docker.pkg.dev

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Start Database
        run: docker compose --project-name msw -f docker-compose.yml up -d

      - name: 🔨 Build
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: 🧪 Test
        run: |
          chmod +x ./gradlew
          ./gradlew test

      - name: 🖨️ Prepare Backend Docker Build
        run: |
          mv backend/build/libs/$(ls backend/build/libs | grep -v plain) backend/app.jar

      - name: 🐳 Build Backend Docker Image
        run: |
          docker build \
            --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$GAR_REPOSITORY_BACKEND/$GITHUB_SHA" \
            --build-arg JAR_FILE=app.jar \
            backend

      - name: 🐳 Build Frontend Docker Image
        run: |
          docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$GAR_REPOSITORY_FRONTEND/$GITHUB_SHA" \
          frontend

      - name: 🚀 Push Backend Image to GCP Artifact Registry
        if: github.ref == 'refs/heads/master'
        run: |
          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$GAR_REPOSITORY_BACKEND/$GITHUB_SHA"

      - name: 🚀 Push Frontend Image to GCP Artifact Registry
        if: github.ref == 'refs/heads/master'
        run: |
          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$GAR_REPOSITORY_FRONTEND/$GITHUB_SHA"
